name: prime
on: [push]
jobs:
   test:
     name: Test
     runs-on: [windows-latest]
     
     steps:
        - uses: actions/checkout@v2
        - name: Setup Java JDK
          uses: actions/setup-java@v3.10.0
          with:
            java-version: 3.10.0
  
        - name: setup java
          run: |
                javac prime.java
                java prime
