name: Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build and package application
      run: mvn package

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
       run: | 
            javac prime.java
  



    
