name: prime
on: [push, pull_request]
jobs:
   test:
     name: Test
     runs-on: windows-latest
     
     steps:
        - uses: actions/checkout@v2
        - name: Setup Java JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: 2

        - name: setup java
          run: |
                javac prime.java
                java prime
